name: Build Jamal
on: [push]
jobs:
  Build on Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build POM files
        run: mvn -f genpom.xml
      - name: Build with Maven
        run: mvn clean verify